### ISSUE TITLE
failure for test "Generating BCrypt hashes should be interoperable with other implementations"

### ISSUE THREAD

**Issue by Segaja** [codahale/bcrypt-ruby#244]
When testing bcrypt 3.1.16 with up to date dependencies, I  get this error:

```
Failures:

  1) Generating BCrypt hashes should be interoperable with other implementations
     Failure/Error: expect(BCrypt::Engine.hash_secret(secret, salt)).to eql(test_vector)

       expected: "$2x$05$/OK.fbVrR/bpIqNJ5ianF.CE5elHaaO4EbggVDjb8P19RukzXSM3e"
            got: nil

       (compared using eql?)
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-support-3.8.0/lib/rspec/support.rb:97:in `block in <module:Support>'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-support-3.8.0/lib/rspec/support.rb:106:in `notify_failure'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-expectations-3.8.1/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-expectations-3.8.1/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-expectations-3.8.1/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-expectations-3.8.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-expectations-3.8.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-expectations-3.8.1/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/bcrypt/engine_spec.rb:154:in `block (3 levels) in <top (required)>'
     # ./spec/bcrypt/engine_spec.rb:153:in `each'
     # ./spec/bcrypt/engine_spec.rb:153:in `block (2 levels) in <top (required)>'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `instance_exec'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `block in run'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `block in run'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `run'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:251:in `run'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:629:in `block in run_examples'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `map'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `run_examples'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:591:in `run'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (3 levels) in run_specs'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `map'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (2 levels) in run_specs'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1989:in `with_suite_hooks'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:111:in `block in run_specs'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:74:in `report'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:87:in `run'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/exe/rspec:4:in `<main>'
```

Any idea how to resolve this?

Best regards
Segaja
